spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        -id: catalogue-service
        -uri: lb://CATALOGUESERVICE
      predicates:
        -path=/catalogue/**
          -id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
          path=/order/**
             -id: payment-service
             uri: lb://PAYMENT-SERVICE
            predicates:
              path=/payment/**
        path=/authenticate/**
          -id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            path=/authenticate/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8088/eureka/
    instance:
      hostname: localhost

server:
  port: 9087

